ALTER TABLE "Producto" ADD COLUMN "marca" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Producto" ADD COLUMN "unidad" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Producto" ADD COLUMN "precioVenta" REAL NOT NULL DEFAULT 0;
